# Generated by Django 6.0.6 on 2026-08-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacorapasaje',
            name='autoriza_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_1', to='bitacoras.usuario'),
        ),
        migrations.AddField(
            model_name='bitacorapasaje',
            name='autoriza_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_2', to='bitacoras.usuario'),
        ),
        migrations.AddField(
            model_name='bitacorapasaje',
            name='autoriza_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_3', to='bitacoras.usuario'),
        ),
        migrations.AddField(
            model_name='bitacorapasaje',
            name='tipo_pasaje',
            field=models.CharField(choices=[('Local', 'Local'), ('Foráneo', 'Foráneo')], default='Foráneo', max_length=20),
        ),
    ]
